@startuml

rectangle "Cliente" as Cliente


package sistema{
    rectangle "Puerto 51413" as Puerto
    rectangle "Cola UDP" as UDP
    rectangle "Cola TCP" as TCP

    database "Servidor Clase A" as ServidorA
    database "Servidor Clase B" as ServidorB
}

Cliente ..> Puerto
Puerto ..> UDP
Puerto ..> TCP
UDP --> ServidorA
UDP --> ServidorB
TCP --> ServidorB

@enduml